apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgres14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: miguel098
            - name:  POSTGRES_DB
              value: mvc_cursos
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc


