version: "3.9"
services:

  #POSTGRESQL
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: miguel098
      POSTGRES_DB: mvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring



  mvc-cursos:
    container_name: mvc-cursos
    image: miguelrodriguez15/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./mvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: mvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: miguel098
      USUARIOS_URL: ec2-3-16-158-91.us-east-2.compute.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:

  data-postgres:
    name: data-postgres


networks:
  spring:
    name: spring

