version: "3.9"
services:
  #MY SQL
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  #POSTGRESQL
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: miguel098
      POSTGRES_DB: mvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring


  mvc-usuarios:
    container_name:  mvc-usuarios
    image: miguelrodriguez15/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./mvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./mvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: always


  mvc-cursos:
    container_name: mvc-cursos
    image: miguelrodriguez15/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./mvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./mvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - mvc-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres


networks:
  spring:
    name: spring

