version: "3.9"
services:
  #MY SQL
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring



  mvc-usuarios:
    container_name:  mvc-usuarios
    image: miguelrodriguez15/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./mvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql:3306
      DB_DATABASE: mvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD:
      CURSOS_URL: ec2-3-17-28-30.us-east-2.compute.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql
    restart: always



volumes:
  data-mysql:
    name: data-mysql



networks:
  spring:
    name: spring

