spring:
  cloud:
    gateway:
      routes:
        - id: mvc-cursos
          uri: lb://mvc-cursos
          predicates:
            - Path=/api/cursos/**
          filters:
            - StripPrefix=2
        - id: mvc-usuarios
          uri: lb://mvc-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2